

import edu.uiuc.cs.TrustBuilder2.messages.X509CredentialBrick;


rule "nameRequired"

when
$cert1 : X509CredentialBrick( getIssuer() == "CN=Acme Fabrication,O=Acme Fabrication,ST=Some-State,C=US")
$cert2 : X509CredentialBrick( getIssuer() == "CN=Acme Fabrication,O=Acme Fabrication,ST=Some-State,C=US")
$cert3: X509CredentialBrick( getIssuer() == "CN=Acme Springfield,O=Acme Springfield,ST=Some-State,C=US" && getFields().get("Type") == "Employee" && isOwnershipVerified() == true )
$credList: java.util.ArrayList()

then

  $credList.add($cert1);
  $credList.add($cert2);
  $credList.add($cert3);
  
  

end